//
// API ENDPOINTS USER
//

// HÄMTA ALLA USERS // SKICKA INTE MED LÖSENORD // BARA ID, NAMN + EMAIL PÅ ALLA USERS
# @name getUsers
GET http://localhost:3000/api/users

###

// HÄMTA SPECIFIK USER // SKICKA HELA OBJEKTET
POST http://localhost:3000/api/users/
Content-Type: application/json

{
  "id": "65c0bb85d04a9432126f6597"
}

###

// SKAPA USER
POST http://localhost:3000/api/users/add
Content-Type: application/json

{
  "name": "Moa Jansson",
  "email": "moaaa@mail.com",
  "password": "test"
}

###

// LOGGA IN USER
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "email": "kalle@mail.com",
  "password": "test"
}

###

//
// API ENDPOINTS PRODUKTER
//

// HÄMTA ALLA PRODUKTER

# @name getProducts
GET http://localhost:3000/api/products

###

// HÄMTA SPECIFIK PRODUKT
GET http://localhost:3000/api/products/65c09c2a2e39495a49d2edcf 
// ID PÅ PRODUKT

###

// SKAPA PRODUKT
POST http://localhost:3000/api/products/add
Content-Type: application/json

{
  "name": "Cheesecake",
  "description": "Cheesecake med smak av citron",
  "price": 150, 
  "lager": 100
}

###

//
// API ENDPOINTS ORDERS
//

// SKAPA ORDER FÖR EN SPECIFIK USER // PRODUCTS ÄR EN ARRAY MOTSVARANDE INNEHÅLLET I KUNDVAGN
POST http://localhost:3000/api/orders/add
Content-Type: application/json

{
  // "user": "{{getUsers.response.body.$[0].id}}",
  "user": "65c0bb85d04a9432126f6597",
      "products": [
    {
      "productId": "65c09c2a2e39495a49d2ede2",
      "quantity": 1
    },
    {
      "productId": "65c0c0989b0b117a17e94a18",
      "quantity": 1
    },
    {
      "productId": "65c20f46d5856b5ffeb5c6c3",
      "quantity": 1
    }
  ]
}

###

// HÄMTA ALLA ORDERS
GET http://localhost:3000/api/orders/all/

###